version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-python-dependencies"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
