version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-python-dependencies"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "deps(python)"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
