name: "Setup Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install Python Dependencies
      shell: bash
      run: just install-all
