name: "Setup Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
    - name: Set up Just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
    - name: Install Python Dependencies
      shell: bash
      run: just install-all
